name: Build Geode Mod

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        required: true
        default: 'debug'
        type: choice
        options:
          - release
          - debug
  push:
    branches:
      - "**"

      
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

        - name: macOS
          os: macos-latest

        - name: Android32
          os: ubuntu-latest
          target: Android32

        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set Release Build
        run: echo "RELEASE_BUILD=${{ github.event.inputs.build_type == 'release' }}" >> $GITHUB_ENV

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          bindings-ref: main
          combine: true
          build-config: ${{ github.event.inputs.build_type != 'release' && 'RelWithDebInfo' || 'Release' }}
          export-pdb: ${{ github.event.inputs.build_type != 'release' }}
          target: ${{ matrix.config.target }}

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ${{ steps.build.outputs.build-output }}

  release: 
    name: Create Release
    runs-on: ubuntu-latest
    needs: ['package']
    permissions:
      contents:
        write
        
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: './artifacts/'

      #- run: |
      #    7z x ./artifacts/build-output.zip

      - uses: andelf/nightly-release@main
        if: github.event.inputs.build_type != 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Development Release'
          body: |
            Development release for commit ${{ github.sha }}. Built in RelWithDebInfo.
          files: |
            ./artifacts/build-output/*.geode
            ./artifacts/build-output/*.pdb

      - name: Declare Version Variable
        if: github.event.inputs.build_type == 'release'
        id: ref
        shell: bash
        run: |
          unzip -o ./artifacts/build-output/*.geode -d ./artifacts/unzipped

          VERSION=$(jq -r '.version' < ./artifacts/unzipped/mod.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          set +e
          curl --fail "https://api.github.com/repos/geode-sdk/geode/releases/tags/v$VERSION" --silent --output /dev/null
          RESULT=$?
          set -e
          
          if [ $RESULT -eq 0 ]; then
            echo "Release $VERSION already exists! Not replacing it.."
            exit 1
      
      - name: Create Draft Release
        uses: softprops/action-gh-release@v1'
        if: github.event.inputs.build_type == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.ref.outputs.version }}
          name: Geode v${{ steps.ref.outputs.version }}
          body: |
            TODO before publishing:
             - mark if pre-release
             - add changelog
             - remove this
          draft: true
          files: |
            ./geode-installer-v${{ steps.ref.outputs.version }}-win.exe
            ./geode-installer-v${{ steps.ref.outputs.version }}-mac.pkg
            ./geode-v${{ steps.ref.outputs.version }}-win.zip
            ./geode-v${{ steps.ref.outputs.version }}-mac.zip
            ./geode-v${{ steps.ref.outputs.version }}-android32.zip
            ./geode-v${{ steps.ref.outputs.version }}-android64.zip
            ./resources.zip